# ---- Base image ----
# Use 3.12 slim for smaller container size with better package compatibility (C-extension support)
# Slim also has faster build speed
FROM Python:3.12-slim

# Where subsequent commands run and where your code will live inside the image.
WORKDIR /app

# --- deps first (optimize layer-caching) ---
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


# ---- App code after install layer because of frequent changes ---
COPY . .

# Documents the port uvicorn listens on. (nginx will proxy to this later.)
EXPOSE 8000

# ---- Runtime ----
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]