"""add users table, FK tracks.user_id --> users.id

Revision ID: 3e5de55e1816
Revises: b97bd0772f8f
Create Date: 2026-07-08 11:00:39.859685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5de55e1816'
down_revision: Union[str, Sequence[str], None] = 'b97bd0772f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('google_identity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('google_identity', name=op.f('uq_users_google_identity'))
    )
    op.create_foreign_key(op.f('fk_tracks_user_id_users'), 'tracks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tracks_user_id_users'), 'tracks', type_='foreignkey')
    op.drop_table('users')
    # ### end Alembic commands ###
