"""add daily_active_users table

Revision ID: 8907ff2c63be
Revises: 3e5de55e1816
Create Date: 2026-07-15 13:39:07.175299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8907ff2c63be'
down_revision: Union[str, Sequence[str], None] = '3e5de55e1816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_active_users',
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('record_date', name=op.f('pk_daily_active_users'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_active_users')
    # ### end Alembic commands ###
